[package]
name = "wg_2024-rust"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["crates/*"]

[dependencies]
log = "0.4.22"
env_logger = "0.11.5"
wg_2024 = { git = "https://github.com/WGL-2024/WGL_repo_2024.git", features = [
    "serialize",
] }
drone = { path = "crates/drone" }
simulation_controller = { path = "crates/simulation_controller" }
crossbeam = "0.8.4"
