[package]
name = "wg_2024-rust"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["crates/*"]

[dependencies]
wg_2024 = { git = "https://github.com/WGL-2024/WGL_repo_2024.git", features = [
    "serialize",
] }
drone = { path = "crates/drone" }
