name: CI

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Run tests
        uses: frequenz-floss/gh-action-cargo-test@v1.0.0
        with:
          cargo-test-parameters: "--lcov --output-path lcov.json"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.json
          fail_ci_if_error: true
